### PR TITLE
Fix #8 linker error in golang 1.5 on darwin.

### LINKED ISSUE #8: illegal text-relocation to _jpeg_resync_to_restart
##### Static link jpeg-turbo (`libjpeg.a`)
```go
#cgo LDFLAGS: /usr/local/opt/jpeg-turbo/lib/libjpeg.a
```

##### ld: illegal text-relocation (`/usr/local/opt/jpeg-turbo/lib/libjpeg.dylib`)
```
/usr/local/Cellar/go/HEAD/libexec/pkg/tool/darwin_amd64/6l: running clang failed: exit status 1
ld: illegal text-relocation to '_jpeg_resync_to_restart' in /usr/local/opt/jpeg-turbo/lib/libjpeg.dylib from 'github.com/pixiv/go-libjpeg/jpeg.init' in /var/folders/7b/6wvl7vm52bz4t29fxktsxbmw0000gn/T/go-link-976456270/go.o for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

~ tree /usr/local/opt/jpeg-turbo/lib/
/usr/local/opt/jpeg-turbo/lib/
├── libjpeg.8.0.2.dylib
├── libjpeg.8.dylib -> libjpeg.8.0.2.dylib
├── libjpeg.a
├── libjpeg.dylib -> libjpeg.8.0.2.dylib
├── libturbojpeg.0.1.0.dylib
├── libturbojpeg.0.dylib -> libturbojpeg.0.1.0.dylib
├── libturbojpeg.a
└── libturbojpeg.dylib -> libturbojpeg.0.1.0.dylib
```

### PR DESCRIPTION
**Pull request by harukasan**
#8 occurs in only golang devel and similar issue reported here: https://github.com/golang/go/issues/9411.
This commit adds a workaround following above issue.

```sh
$ go version
go version devel +0b9866f Sun May 17 01:40:33 2015 +0000 darwin/amd64

$ go build -v ./jpeg/
github.com/pixiv/go-libjpeg/rgb
github.com/pixiv/go-libjpeg/jpeg

bash-3.2$ go test -v ./jpeg/
=== RUN   TestDecode
 - test: cosmos.jpg
 - test: kinkaku.jpg
--- PASS: TestDecode (1.90s)
=== RUN   TestDecodeScaled
 - test: cosmos.jpg
 - test: kinkaku.jpg
--- PASS: TestDecodeScaled (0.12s)
=== RUN   TestDecodeIntoRGBA
--- SKIP: TestDecodeIntoRGBA (0.00s)
	jpeg_test.go:109: This build is not support DecodeIntoRGBA.
=== RUN   TestDecodeScaledIntoRGBA
--- SKIP: TestDecodeScaledIntoRGBA (0.00s)
	jpeg_test.go:128: This build is not support DecodeIntoRGBA.
=== RUN   TestDecodeScaledIntoRGB
 - test: cosmos.jpg
 - test: kinkaku.jpg
--- PASS: TestDecodeScaledIntoRGB (0.13s)
=== RUN   TestDecodeSubsampledImage
 - test: checkerboard_444.jpg
 - test: checkerboard_440.jpg
 - test: checkerboard_422.jpg
 - test: checkerboard_420.jpg
--- PASS: TestDecodeSubsampledImage (0.07s)
=== RUN   TestDecodeAndEncode
 - test: cosmos.jpg
 - test: kinkaku.jpg
--- PASS: TestDecodeAndEncode (0.02s)
=== RUN   TestDecodeAndEncodeSubsampledImages
 - test: checkerboard_444.jpg
 - test: checkerboard_440.jpg
 - test: checkerboard_422.jpg
 - test: checkerboard_420.jpg
--- PASS: TestDecodeAndEncodeSubsampledImages (0.01s)
=== RUN   TestDecodeConfig
 - test: cosmos.jpg
 - test: kinkaku.jpg
--- PASS: TestDecodeConfig (0.00s)
=== RUN   TestNewYCbCrAlignedWithLandscape
--- PASS: TestNewYCbCrAlignedWithLandscape (0.00s)
=== RUN   TestNewYCbCrAlignedWithPortrait
--- PASS: TestNewYCbCrAlignedWithPortrait (0.00s)
PASS
ok  	github.com/pixiv/go-libjpeg/jpeg	2.289s
```

### CODE REVIEW

File: jpeg/sourceManager.go [hunk 1]
```diff
@@ -105,7 +109,7 @@ func makeSourceManager(src io.Reader, dinfo *C.struct_jpeg_decompress_struct) (m
 	mgr.pub.init_source = (*[0]byte)(C.sourceInit)
 	mgr.pub.fill_input_buffer = (*[0]byte)(C.sourceFill)
 	mgr.pub.skip_input_data = (*[0]byte)(C.sourceSkip)
-	mgr.pub.resync_to_restart = (*[0]byte)(C.jpeg_resync_to_restart) // default implementation
+	mgr.pub.resync_to_restart = (*[0]byte)(C.get_jpeg_resync_to_restart()) // default implementation
```
Comment (edvakf) [inline jpeg/sourceManager.go]: is this comment still needed?

```
// default implementation
```

**Comment by edvakf** [comment]
I suggest we wait to merge this until go 1.5 gets released. The code seems like an unnecessary increase of complexity.

**Comment by mattn** [comment]
I'm thinking this change is safe for both of 1.4/1.5.

**Comment by mattn** [comment]
i suggest to add `_` prefix for `get_jpeg_resync_to_restart`.

**Comment by harukasan** [comment]
Thank you for your suggestion. I renamed function name and add bit comments.
